import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { ThemeProvider } from '@/components/theme-provider';
import Header from './components/header';
import Filter from './components/filter';
import TodoList from './components/todo-list';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-full`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="h-full flex flex-col">
            <Header />
            <div className="max-w-7xl mx-auto grow-1 flex justify-center px-4">
              <div className="flex w-full max-w-full">
                {/* První sloupec - max 300px */}
                <div className="max-w-[300px] w-full">
                  <Filter />
                  <TodoList />
                </div>

                {/* Druhý sloupec - zbytek */}
                <div className="flex-1">
                  {/* Obsah druhého sloupce */}
                  {children}
                </div>
              </div>
            </div>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
