import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { ThemeProvider } from '@/components/theme-provider';
import Header from './components/header';
import TodoList from './components/todo-list';
import TodoToolbar from './components/todo-toolbar';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-full`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="h-full flex flex-col">
            <Header />

            <div className="flex-grow pt-4 overflow-hidden">
              <div className="h-full max-w-7xl mx-auto flex justify-center px-4 overflow-hidden">
                <div className="flex w-full max-w-full h-full">
                  {/* První sloupec - max 300px */}
                  <div className="max-w-[300px] w-full h-full flex flex-col">
                    <TodoToolbar />
                    <div className="flex-grow overflow-auto">
                      <TodoList />
                    </div>
                  </div>

                  {/* Druhý sloupec - zbytek */}
                  <div className="flex-1">
                    {/* Obsah druhého sloupce */}
                    {children}
                  </div>
                </div>
              </div>
            </div>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
